language: objective-c

rvm:
  - "2.2"
  - "2.1"
  - "2.0"
  - "1.9"

bundler_args: "--without debug --jobs 3"

sudo: false

script:
  - bundle exec rake spec
  - bundle exec rake spec_without_fakefs
  - bundle exec rake test
  - bundle exec rake test_without_fakefs

cache:
  bundler: true
  directories:
    - node_modules
    - bower_components
